package typedfetch

import (
	"strings"

	"github.com/swaggest/openapi-go/openapi31"
)

func GenerateTypedFetch(reflector *openapi31.Reflector) (string, error) {
	lines := []string{
		"// Code generated by typed-fetch. DO NOT EDIT.",
		"// https://github.com/RPGillespie6/typed-fetch",
		"",
	}

	// Generate all url types
	lines = append(lines, generateUrlTypes(reflector)...)

	// Generate all component types
	componentTypesLines, err := generateComponentSchemaTypes(reflector)
	if err != nil {
		return "", err
	}
	lines = append(lines, componentTypesLines...)

	// Generate all param types
	paramTypesLines, err := generateRequestTypes(reflector)
	if err != nil {
		return "", err
	}
	lines = append(lines, paramTypesLines...)

	// Generate client class
	clientLines := generateClient(reflector)
	lines = append(lines, clientLines...)

	return strings.Join(lines, "\n"), nil
}
